### PR TITLE
feat: better xdg log placement

### PR DESCRIPTION
**Pull request by houlahaj**

### CODE REVIEW

**Comment by emersion** [comment]
https://wiki.debian.org/XDGBaseDirectorySpecification#state

**Comment by houlahaj** [comment]
Until the proposal is standardised, why not conform to the latest spec? https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by emersion** [comment]
The latest spec doesn't say where log files should be stored. Log files definitely aren't cache files.

**Comment by houlahaj** [comment]
I would also argue log files are not state; why lump them together with real state information? They show what the state was at some point in time but have no bearing on what the state of an app will be the next time it is started.

**Comment by emersion** [comment]
The state proposal specifically mention logfiles as a use-case.

**Comment by houlahaj** [comment]
I'm aware of that and would nonetheless maintain that it is a poor example of a use case. If it becomes standardised, then sure. But until then, as it is just a proposal, I feel I'm free to argue against it.

**Comment by emersion** [comment]
The fact that this is not standardized is a fair point. The main reason why I'm not a fan of using the cache dir is that it may be tmpfs, which would be lost on reboot. Other locations aren't great either, for sure we don't want to use the config dir because that would potentially sync logs across devices.

Maybe it's better to just use the cache dir as you suggested.

BTW, why did you close this PR?

**Comment by houlahaj** [comment]
Yeah, no doubt config is the wrong place for logs. It's just a question of how persistent we want logs to be. In most cases, I'd expect a user who has gone to the trouble of putting their cachedir on tmpfs to also want application logs to be cleared as well. But that's just a hunch, no data to back it up.

I closed it temporarily because I forgot to include the commit which made the tests pass. Then you commented 1 minute later and I have yet to reopen it haha

**Comment by emersion** [comment]
Yeah, I agree with that rationale. In any case, this is more of an upstream issue for the xdg spec than a go-appdir issue.

Feel free to re-open. The README will need to be updated as well.

**Pull request closed without merging**
